---
name: leadership-election

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

releases:
- name: leadership-election
  version: latest

instance_groups:
- name: leadership-election
  azs:
  - z1
  instances: 1
  vm_type: minimal
  stemcell: default
  networks:
  - name: default
  jobs:
  - name: leadership-election
    release: leadership-election
    properties:
      port: 8080

update:
  canaries: 1
  max_in_flight: 1
  canary_watch_time: 30000-60000
  update_watch_time: 5000-60000
  serial: true
