#!/bin/bash -e

RUN_DIR=/var/vcap/sys/run/leadership-election
LOG_DIR=/var/vcap/sys/log/leadership-election
PIDFILE=${RUN_DIR}/leadership-election.pid
JOB_DIR=/var/vcap/jobs/leadership-election

PACKAGE_DIR=/var/vcap/packages/leadership-election
ENVIRONMENT=/var/vcap/jobs/leadership-election/bin/environment.sh

case $1 in

  start)
    set +e
      killall -15 leadership-election
      killall -9 leadership-election
      killall -2 leadership-election
      killall -3 leadership-election
    set -e

    mkdir -p $RUN_DIR $LOG_DIR
    chown -R vcap:vcap $RUN_DIR $LOG_DIR

    cd $PACKAGE_DIR

    ulimit -n 8192

    source $ENVIRONMENT
    echo $$ > $PIDFILE
    exec chpst -u vcap:vcap ./leadership-election &>> ${LOG_DIR}/leadership-election.log

    ;;

  stop)
    set +e
      killall -15 leadership-election
      killall -9 leadership-election
      killall -2 leadership-election
      killall -3 leadership-election
    set -e

    rm -f $PIDFILE

    ;;

  *)
    echo "Usage: ctl {start|stop}"

    ;;

esac
